apiVersion: batch/v1
kind: Job
metadata:
  name: strand-worker-template   # not used directly; ScaledJob will template pods
  namespace: agents
spec:
  template:
    spec:
      serviceAccountName: strand-agents-sa
      restartPolicy: Never
      containers:
      - name: worker
        image: <acct>.dkr.ecr.us-east-1.amazonaws.com/strand-agent:latest
        command: ["python", "worker.py"]
        env:
          - name: AWS_REGION
            value: "us-east-1"
          - name: SQS_QUEUE_URL
            value: "https://sqs.us-east-1.amazonaws.com/<acct>/strand-agent-jobs"
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: agent-secrets
                key: OPENAI_API_KEY